<?php
if (!defined('REGLOGDIR')) die();

function checkEmail($email) {
  if(preg_match("/^([a-zA-Z0-9])+([a-zA-Z0-9\._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9\._-]+)+$/", $email)){
    list($username,$domain)=explode('@',$email);
    if(checkdnsrr($domain.'.','MX')) return true;
  }
  return false;
}

function checkreg() {
  global $errmsg;
  $err=0;
  if (isset($_POST['reg_name']) && strlen($_POST['reg_name']) < 2) {
    $errmsg.='<p class="error">* Please give your family name.</p>'."\n";
    $err|=1;
  }

  if (isset($_POST['reg_prename']) && strlen($_POST['reg_prename']) < 2) {
    $errmsg.='<p class="error">* Please enter your given name(s).</p>'."\n";
    $err|=1;
  }

  if (isset($_POST['reg_city']) && strlen($_POST['reg_city']) < 3) {
    $errmsg.='<p class="error">* Please enter your city.</p>'."\n";
    $err|=1;
  }

  if (isset($_POST['reg_country']) && $_POST['reg_country'] == '') {
    $errmsg.='<p class="error">* Please specify your country.</p>'."\n";
    $err|=1;
  }

  if (isset($_POST['reg_email']) && !checkEmail($_POST['reg_email'])) {
    $errmsg.='<p class="error">* Please specify a vaild email address.</p>'."\n";
    $err|=1;
  }

  if (isset($_POST['reg_email_confirm']) && $_POST['reg_email_confirm']!='') {
    $errmsg.='<p class="error">Hello Spam Bot. Human users: Please leave the reg_email_confirm field empty.</p>'."\n";
    $err|=1;
  }

  return (isset($_POST['reg_name']) && $err==0);
}

function format_registration($a) {
  return '
  Name        : '.rawurldecode($a['reg_name']).'
  First Name  : '.rawurldecode($a['reg_prename']).'
  Tagline     : '.rawurldecode($a['reg_tagline']).'
  Email       : '.rawurldecode($a['reg_email']).'
  Age         : '.preg_replace('/A(\d{2})(.{2})/','${1}-${2}',rawurldecode($a['reg_agegroup'])).'
  City        : '.rawurldecode($a['reg_city']).'
  Country     : '.rawurldecode($a['reg_country']).'
  Profession  : '.rawurldecode($a['reg_profession']).'
  Proceedings : '
  .(rawurldecode($a['reg_proceedings'])?'yes':'no')     .'
  Uses Linux  : '
  .(rawurldecode($a['reg_useathome'])?'at home, ':'_not_ at home, ')
  .(rawurldecode($a['reg_useatwork'])?'at work' :'_not_ at work' )  .'
  Pro Audio   : '
  .((rawurldecode($a['reg_audiopro'])==1)?'no':'')
  .((rawurldecode($a['reg_audiopro'])==2)?'yes':'')
  .((rawurldecode($a['reg_audiopro'])==0)?'??':'')
  .'
  Interests   : '  # TODO use pages/registration.php -> $about array
.($a['reg_vmusician']?'Musician or composer, ':'')
.($a['reg_vdj']?'DJ, ':'')
.($a['reg_vswdeveloper']?'Software Developer, ':'')
.($a['reg_vhwdeveloper']?'Hardware Developer, ':'')
.($a['reg_vswuser']?'Software User, ':'')
.($a['reg_vmediapro']?'Media Professional, ':'')
.($a['reg_vmproducer']?'Music Producer, ':'')
.($a['reg_vvproducer']?'Video Producer, ':'')
.($a['reg_vresearcher']?'Researcher, ':'')
.($a['reg_vpress']?'Press, ':'')
.($a['reg_vinterested']?'Just interested, ':'')
.($a['reg_vother']?'Other ':'')
.'
  Food        : '.rawurldecode($a['reg_food']).'

  Notes       : '.rawurldecode($a['reg_notes']).'
';
}

function savereg() {
  $name = preg_replace('/[^a-zA-Z0-9]/','_', $_POST['reg_prename'].'_'.$_POST['reg_name']);
  $fname = REGLOGDIR .date("Ymd_His").'-'.$name.'.ini';
  $handle = fopen($fname, "a");
  if (!$handle) {
    global $errmsg;
    $errmsg.='<p class="error">Error in storing your registration. We apologize for the inconvenience.<br/>';
    $errmsg.='Please inform us about your problem: Send an email to robin AT linuxaudio DOT org.</p>';
    return false;
  }
  $datafields=array(
    'reg_name', 'reg_prename', 'reg_tagline', 'reg_email', 'reg_agegroup', 
    'reg_city', 'reg_country', 'reg_useathome', 'reg_useatwork', 
    'reg_audiopro', 'reg_vmusician', 'reg_vdj', 'reg_vswdeveloper',
    'reg_vhwdeveloper', 'reg_vswuser', 'reg_vpress',
    'reg_vmediapro', 'reg_vmproducer', 'reg_vvproducer', 'reg_vresearcher',
    'reg_vinterested', 'reg_vother', 'reg_profession',
    'reg_proceedings', 'reg_food', 'reg_notes'
  );

  #store in .ini file format -> human readable and 
  #parseable with PHP's parse_ini_file()
  fwrite($handle, '; Registration for user: '.$name."\n");
  foreach ($datafields as $k) {
    fwrite($handle, $k.'="'.preg_replace('/[";]/','.',rawurldecode($_POST[$k]))."\"\n");
  }
  fwrite($handle, "\n");
  fclose($handle);

  # TODO: send email
  $subject='LAC2010 registration: '.preg_replace('/[^a-zA-Z0-9 ,]/','', $_POST['reg_prename'].' '.$_POST['reg_name']);
  $message='Dear LAC2010 Organizers,

A new participan has registered. Here are the details:
'.format_registration($_POST).'

  Browser used: '.$_SERVER['HTTP_USER_AGENT'].'

-- 
This mail was generated by http://lac.linuxaudio.org/2010/

';

# $message.=print_r(parse_ini_file($fname),true);

  $headers = 'From: lac@linuxaudio.org';

  global $mailto;
  if (!empty($mailto)) 
    mail($mailto, $subject, wordwrap($message,70), $headers);

  return true; 
}
